name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["main", "dev"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: metrics-head.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Manila
          base: header
          base_indepth: yes
      - uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Manila
          base: activity, community, repositories, metadata
          base_indepth: yes
          # plugin_achievements: yes
          # plugin_achievements_threshold: C
          # plugin_achievements_display: detailed
          # plugin_achievements_only: >-
          #   polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
          #   scripter, packager, explorer, infographile, manager
          # plugin_languages: yes
          # plugin_languages_indepth: yes
          # plugin_languages_analysis_timeout_repositories: 15
          # plugin_languages_details: lines, bytes-size, percentage
          # config_order: achievements, base.repositories, languages, habits, base.activity, base.community, base.metadata
          config_order: base.repositories, habits, base.activity, base.community, base.metadata
