name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["main", "dev"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Create header info asset
        uses: lowlighter/metrics@master
        with:
          filename: metrics-head.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Manila
          base: header
          base_indepth: yes
          config_padding: -32px, 8px
      - name: Create metrics content asset
        uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Manila
          base: activity, community, repositories
          base_indepth: yes
          config_order: base.repositories, habits, base.activity, base.community
          config_padding: -200px, 32px
      - name: Create footer metadata asset
        uses: lowlighter/metrics@master
        with:
          filename: metrics-foot.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Manila
          base: metadata
          base_indepth: yes
          config_padding: -32px, 16px
  render-contribs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create total contributions sheet
        uses: salty-sweet/render-contribs@dev
        with:
          github_token: ${{ secrets.METRICS_TOKEN }}
          zone: "Asia/Manila"
          custom_theme: "{\"background\": \"#ff000000\",\"text\": \"#be8148\",\"meta\": \"#6d6159\",\"grade0\": \"#3a3533\",\"grade1\": \"#90ca96\",\"grade2\": \"#4da26a\",\"grade3\": \"#298258\",\"grade4\": \"#eaba73\"}"
          output_path: "./contribs.png"
        
      # - uses: lowlighter/metrics@master
      #   with:
      #     filename: metrics-lang.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     config_timezone: Asia/Manila
      #     base: ""
      #     plugin_languages: yes
      #     plugin_languages_indepth: yes
      #     plugin_languages_sections: recently-used
      #     plugin_languages_limit: 6
      #     plugin_languages_analysis_timeout_repositories: 15
      #     plugin_languages_recent_categories: data, markup, programming, prose
      #     plugin_languages_recent_days: 365
      #     # plugin_languages_details: lines, bytes-size, percentage
      #     # config_order: achievements, base.repositories, languages, habits, base.activity, base.community, base.metadata
      #     config_padding: 0, 16px
